<div class="box3">
  <ul class="numbered-list numbered-list-1">
    <li>
        <a href="#">Micro-Anlagen</a>
        <span>79</span>
    </li>
    <li>
        <a href="#">Stereo-Receiver/Verstärker</a>
        <span>50</span>
    </li>
    <li>
        <a href="#">AV-Receiver</a>
        <span>47</span>
    </li>
    <li>
        <a href="#">CD-Player/Wechsler</a>
        <span>15</span>
    </li>
    <li>
        <a href="#">Plattenspieler</a>
        <span>11</span>
    </li>
    <li>
        <a href="#">Kassettendecks</a>
        <span>1</span>
    </li>
  </ul>
  
  <a href="#" class="filterLink">Zurück</a>
</div>
