<h2>Grundlagen von CSS</h2>

<p>Mit CSS geben wir der Struktur der XHTML-Seite Form und Gestaltung. Wir haben dabei vier Möglichkeiten, um die Gestaltung an das XHTML-Objekt zu bringen.</p>

<ul>
  <li>Über die direkte Ansprache eines Tags.</li>
  <li>Über die Ansprache einer Klasse.</li>
  <li>Über die Ansprache einer ID.</li>
  <li>Über die Ansprache einer Pseudoklasse (bspw. a:hover)</li>
</ul>
