<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <title>Styleguide</title>
  <style>
    /* styling basics */
    html {padding: 20px 0; background-color: #efefef;}
    body {width: 80%; padding: 40px; margin: 0 auto; background: #fff; box-shadow: 1px 1px 5px rgba(0,0,0,0.5); font-family: Verdana, Arial, sans-serif; font-size: 16px;position: relative;}
    h1 {font-size: 20px; font-weight: normal;}
    ul {margin: 20px 0;}
  </style>
</head>
<body>
