<form action="/" class="ym-form">
  <div class="ym-fbox ym-g50">
    <label for="emailReg">E-Mail Adresse*</label>
    <input id="emailReg" name="email" class="text" type="text" required>
  </div>
  <div class="ym-fbox ym-g50">
    <label for="pwReg1">Passwort (mind. 6 Zeichen)</label>
    <input id="pwReg1" name="pwReg1" class="text" type="password">
  </div>
  <div class="ym-fbox ym-g50">
    <label for="pwReg1">Passwort wiederholen</label>
    <input id="pwReg2" name="pwReg2" class="text" type="password">
  </div>

  <ul class="noList options">
    <li><a href="#">Bereits registriert?</a></li>
  </ul>

  <div class="ym-fbox-footer ym-clearfix">
    <input value="Registrieren" name="registrieren" type="submit">
  </div>
</form>
