<!doctype html>
<html lang="de">
<head>
	<meta charset="utf-8">
	<title><?php if (isset($pagetitle)) {echo $pagetitle;} else { echo "Platzhalter für einen Seitentitel";} ?></title>

	<script>document.documentElement.className += " js";</script>

	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="icon" href="favicon.ico">
	<link rel="stylesheet" href="css/css.css" type="text/css">
	<script src="js/jquery.min.js" type="text/javascript"></script>
</head>

<body>

	<!-- begin: skip link navigation -->
	<?php include 'inc/modules/skiplinks.inc'; ?>
	<!-- end: skip link navigation -->

	<div class="wrapper">
