<blockquote>
	<p>
		Auch gibt es niemanden, der den Schmerz an sich liebt,
		sucht oder wünscht, nur, <strong>weil er Schmerz ist</strong>,
		es sei denn, es kommt zu zufälligen Umständen,
		in denen Mühen und Schmerz ihm große Freude bereiten können.
		Um ein triviales Beispiel zu nehmen, wer von uns unterzieht
		sich je anstrengender körperlicher Betätigung, außer um
		Vorteile daraus zu ziehen?
		Aber wer hat <em>irgend ein Recht</em>, einen Menschen zu
		tadeln, der die Entscheidung trifft, eine Freude zu genießen,
		die keine unangenehmen Folgen hat, oder einen, der Schmerz
		vermeidet, welcher keine daraus resultierende Freude
		nach sich zieht?
	</p>
</blockquote>
