<div>
    <select name="bundeslaender" size="1">
    	<option value="" selected="selected">Bitte auswählen</option>
    	<option value="01">Baden-Württemberg</option>
    	<option value="02">Bayern</option>
    	<option value="03">Berlin</option>
    	<option value="04">Brandenburg</option>
    	<option value="05">Bremen</option>
    	<option value="06">Hamburg</option>
    	<option value="07">Hessen</option>
    	<option value="08">Mecklenburg-Vorpommern</option>
    	<option value="09">Niedersachsen</option>
    	<option value="10">Nordrhein-Westfalen</option>
    	<option value="11">Rheinland-Pfalz</option>
    	<option value="12">Saarland</option>
    	<option value="13">Sachsen</option>
    	<option value="14">Sachsen-Anhalt</option>
    	<option value="15">Schleswig-Holstein</option>
    	<option value="16">Thüringen</option>
    </select>
</div>
