<div>
  <label for="text-input">type="text"</label>
  <input type="text" id="text-input">
</div>
<div>
    <label for="password-input">type="password"</label>
    <input type="password" id="password-input">
</div>
<div>
  <label for="number-input">type="number"</label>
  <input type="number" id="number-input">
</div>
<div>
  <label for="email-input">type="email"</label>
  <input type="email" id="email-input">
</div>
<div>
  <label for="url-input">type="url"</label>
  <input type="url" id="url-input">
</div>
<div>
  <label for="search-input">type="search"</label>
  <input type="search" id="search-input">
</div>
<div>
  <label for="tel-input">type="tel"</label>
  <input type="tel" id="tel-input">
</div>
<div>
    <label for="datetime-input">type="datetime"</label>
    <input type="datetime" id="datetime-input">
</div>
<div>
  <label for="datetime-local-input">type="datetime-local"</label>
  <input type="datetime-local" id="datetime-local-input">
</div>
<div>
  <label for="date-input">type="date"</label>
  <input type="date" id="date-input">
</div>
<div>
  <label for="month-input">type="month"</label>
  <input type="month" id="month-input">
</div>
<div>
  <label for="time-input">type="time"</label>
  <input type="time" id="time-input">
</div>
<div>
  <label for="week-input">type="week"</label>
  <input type="week" id="week-input">
</div>
<div>
  <label for="checkbox-input">Checkbox</label>
  <input type="checkbox" id="checkbox-input">
</div>
<div>
    <label for="radio-input">Radio-Button</label>
    <input type="radio" id="radio-input">
</div>
<div>
  <label for="color-input">type="color"</label>
  <input type="color" id="color-input">
</div>
<div>
  <label for="file-input">type="file"</label>
  <input type="file" id="file-input">
</div>
<div>
  <label for="image-input">type="image"</label>
  <input type="image" id="image-input" src="http://placehold.it/60x20&text=Senden" alt="Senden">
</div>
