<div>
  <label>South American countries</label><br>
  <input list="countries" placeholder="Type a country">

  <datalist id="countries">
    <option value="Argentina"></option>
    <option value="Bolivia"></option>
    <option value="Brazil"></option>
    <option value="Chile"></option>
    <option value="Colombia"></option>
    <option value="Ecuador"></option>
    <option value="Guyana"></option>
    <option value="Paraguay"></option>
    <option value="Peru"></option>
    <option value="Suriname"></option>
    <option value="Uruguay"></option>
    <option value="Venezuela"></option>
  </datalist>
</div>
<!-- Das schliessende </option> ist nur für den Validator innerhalb von php2html wichtig.
     Notwendig ist es laut Spezifikation nicht. -->
