<table class="data">
  <tr>
    <th>Tabellenüberschrift 1</th>
    <th>Tabellenüberschrift 2</th>
    <th>Tabellenüberschrift 3</th>
    <th>Tabellenüberschrift 4</th>
  </tr>
  <tr>
    <td>1. Eintrag in der ersten Zeile</td>
    <td>2. Eintrag in der ersten Zeile</td>
    <td>3. Eintrag in der ersten Zeile</td>
    <td>4. Eintrag in der ersten Zeile</td>
  </tr>
  <tr>
    <td>1. Eintrag</td>
    <td>2. Eintrag</td>
    <td>3. Eintrag</td>
    <td>4. Eintrag</td>
  </tr>
  <tr>
    <td>1. Eintrag in der letzten Zeile</td>
    <td>2. Eintrag in der letzten Zeile</td>
    <td>3. Eintrag in der letzten Zeile</td>
    <td>4. Eintrag in der letzten Zeile</td>
  </tr>
</table>
