<table summary="Table summary">
	<caption>Table Caption</caption>
	<thead>
		<tr>
			<th>H. C. Andersens 1</th>
			<th>MÄRCHEN FÜR KINDER 2</th>
			<th>Märchengruß 3</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1a – Hans Andersen, der Märchendichter, Nennt man ihn nur, landaus, landein; Da lachen strahlende Gesichter, Da jubeln Bub´ und Mägdelein! Ihm sang und klang, ihm lebt´ und lachte, Was anderer Ohr und Auge tot, Das Seelenlose fühlt´ und dachte Und ward beseelt, – wenn er gebot.</td>
			<td>2a – Den er gepflückt im Wunderlande, Den allerschönsten Märchenstrauß, Geknüpft mit rot und weißem Bande, Streut´ einst er in die Welt hinaus. Und aus dem Strauß die zart´sten Triebe, Die er bestimmt der Kinderschar, Sind hier gesammelt euch zuliebe; Wir bieten sie euch freudig dar.</td>
			<td>3a – Längst ist er schon von uns gegangen, Der Dichter, der den Kindern lieb, Doch leben noch in Jugendprangen Die Märchen, die für euch er schrieb. Sie klingen fort und werden klingen Unsterblich noch in später Zeit, Und sich wie gold´ne Fäden schlingen Um Kind und Märchenherrlichkeit.</td>
		</tr>
		<tr>
			<td>1b –   Des grauen Entleins Abenteuer, Der Zinnsoldat, auf einem Bein Standhaft im Wasser und im Feuer, Die Schwäne und ihr Schwesterlein; Das Märlein von dem Tannenbaume, Vom Koffer, der die Luft durchschwirrt, Vom Sandmann und Klein–Hjalmars Traume, Vom Tölpelhans, der König wird.</td>
			<td>2b –   Sie wollen plaudern, wollen scherzen, Sie wollen bei euch Kindern sein, Und dringen in die Kinderherzen Mit ernster Lehre mahnend ein. – So macht dem luftigen Gelichter Ein Heim in Herz und Haus bereit, Und seid gegrüßt vom Märchendichter, Die ihr ja selber Märchen seid!</td>
			<td>3b –  – Längst ist er schon von uns gegangen, Der Dichter, der den Kindern lieb, Doch leben noch in Jugendprangen Die Märchen, die für euch er schrieb. Sie klingen fort und werden klingen Unsterblich noch in später Zeit, Und sich wie gold´ne Fäden schlingen Um Kind und Märchenherrlichkeit.</td>
		</tr>
	</tbody>
</table>
